### ISSUE TITLE
spring-session unwork

### ISSUE THREAD

**Issue by lvdong** [jdonee/Spring-boot-shiro-spring-session-redis-example#1]
我加了DefaultWebSessionManager 这个bean后springsession就工作了。但是如果不加DefaultWebSessionManager ，redis缓存每次都会添加一条记录。相当于缓存没生效。不知道是什么原因

**Comment by jdonee** [comment]
因为Shiro有自己的缓存管理器，而Spring session依赖于Web Session管理器，你去掉了DefaultWebSessionManager，相当于就是去掉了springsession的控制。
